### ISSUE TITLE
GSS does not update/relayout when removing class

### ISSUE THREAD

**Issue by johanneseckert** [gss/engine#101]
GSS does not seem to respect removing a class with `document.getElementById("cell").classList.remove("square")`, although I see a layout pass in the console immediately after—I expected the width to be determined by window after removing the class `square` on the element.

Same happens with `classList.add`
### setup

``` css
        .cell {
            width: == ::window[width] - 200;
            height: == ::[width];
                }

        .cell.square {
            width: == 300;
            height: == ::[width];
        }
```

``` html
        <main class="cell square" id="cell">
                  foo
        </main>
```
