### ISSUE TITLE
Normal CSS props not working correctly

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#11]
Regular CSS should work within a GSS style sheet like:

``` css
#css-only {
  color: purple;
}
```

As well as with nested rules:

``` css
.outer, .outie {
  #css-inner-dump-1 {
    width: == 100;
    height: 100px;
  }
  .innie-outie {
    #css-inner-dump-2 {
      height: 200px;
    }
  }
}
```

But, the hard part is getting it to work within @if @else conditionals...
