### ISSUE TITLE
Contextual Conditionals

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#12]
[Media Queries are a hack](http://ianstormtaylor.com/media-queries-are-a-hack/).  In order to achieve the power of the hypothically awesome power of [Element Queries](http://www.xanthir.com/b4PR0) we need the following contrived example to work:

``` css
#box1[width] == 720;
#box2[width] == 600;

.box {
  @if ::[width] < 700 {
    height: == 200;
  }
  @else {
    height: == 400;
  }
}
```
