### ISSUE TITLE
@if compare two element's properties / collision detection

### ISSUE THREAD

**Issue by johanneseckert** [gss/engine#128]
I am trying to detect when the edges of two elements meet, but I can't seem to get a response (the `top` and `background` are totally for debug only).

``` css
  @if #title[left] <= #label[right] {
    #header {
      top: == 30;
      background: blue;
    }
  } @else {
    #header {
      top: == 0;
    }
  }
```

is there a better way to detect collision?

check this example: http://jsbin.com/zicumi/27
