### ISSUE TITLE
Conditional creates infinite loop

### ISSUE THREAD

**Issue by johanneseckert** [gss/engine#129]
I'm isolating a question/problem that I mentioned in #128:

There's a conditional that checks the distance between two objects. That check can be performed without problems, and changes in the conditional take affect. However, if one of the changes actually change the condition that was checked (i.e. affecting the distance of two objects), the layout pass seem to get stuck in a loop until the browser times it out.

**Here's the example: http://jsbin.com/cotoke/11**
_Open with care, as this example may crash your browser/tab if it gets too narrow._
# box2 wants to be centered, but it will also get pushed out by #box1

``` css
  #box2 {
    width: == ::[intrinsic-width] !require;
    center-x: == ::window[center-x];

    /* allow to be pushed by #box1 */
    left: >= #box1[right] !require;
  }
```

I am checking the distance between #box2 and #box3 and change the width of #box1 when there is no more space left. The idea is that this will free up some space again.

``` css
  [check] == #box3[left] - #box2[right];

  @if [check] <= 0 {
    /* if there is no space */
    #box1 {
      background: red;
      right: == 200 !strong;
    }
  } @else {
    /* if there is space */
    #box1 {
      background: green;
      right: == 300 !require;
    }
  }
```

If you take out #box1[right] from the conditional and define it outside, the color change takes effect as expected (which I take as indication that the condition is defined correctly)

![screen shot 2014-12-12 at 5 05 25 pm](https://cloud.githubusercontent.com/assets/545926/5421835/118347f4-8221-11e4-92cd-e736b29d5d09.png)

This is the real example where I am trying to accopmplish this: http://jsbin.com/zicumi/88
