### ISSUE TITLE
Nested Conditionals

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#13]
Currently, `@if` `@else` conditionals cannot be nested like so:

``` css
@if ::window[width] >= 960 {
  .box {
    @if ::[width] < 700 {
      height: == 200;
    }
    @else {
      height: == 400;
    }
  }
}
```
