### ISSUE TITLE
Parent Ref (^) doesnt work

### ISSUE THREAD

**Issue by OClement** [gss/engine#176]
See [This Plunk](http://plnkr.co/edit/qPAzS9lIYtwKM9gB2zP5?p=preview) as reference

According to the docs and examples, doing so should work:

```less
.container {
  size: == 500;
  
  .box1 {
    width: == ^[width] / 2; /* doesnt work */
    height: == 250;
  
    .box2 {
      height: == ^[height] / 2; /* doesnt work */
    }
  }

}

```

But it doesn't for me, in various scenarios
The values returned are always 0
