### ISSUE TITLE
Full transform support - rotate, skew, scale, anchor-point

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#18]
## Local-to-global issues

Will be tough to minimize API surface and allow relative positioning & sizing across transform contexts.  For example" 

``` css
#box {
  rotate: == 45;
  center-x: == ::window[center-x];
  width: == 100;
  #inner-box {
    rotate: == 45;
    width: == 100;
    center-x: == ::window[center-x];
  }
}
```

Are `#box` and `#inner-box` centered within window?  Would prefer not to have to fiddle with `transform-origin`.  `toLocal()` & `toGlobal()` property functions would be nice to use in constraints, but, scaling or rotating by a constraint variable make constraint expressions go nonlinear, assuming the constraints span transform contexts...  

Assuming global _position_ context so that the above `#box` and `#inner-box` would indeed be centered sounds nice...  But, _sizes_ should not be assumed orthogonal to the global transform context, otherwise the two above boxes would be scaled by different amounts to maintain a horizontal width of 100px parallel to the top of the screen.  And, unfortunately, `center-x` is an expression of _size_ & _position_.   What about `left` `top`, `right` & `bottom`?  Can of worms.
## Anchor point

Might as well throw in `anchor-point` while I'm at it.  I've always preferred the semantics of Adobe After Effects's "anchor-point" over "transform-origin":  
- _align by anchor-points_ vs. _align by transform-origin_
- `#hole[center] == #wall[anchor-point]` vs. `#hole[center] == #wall[transform-origin]`
## Setting the transform prop

Do the math before setting `matrix3d` or add props other than `matrix3d`?  Probably stick with doing the matrix math manually.
