### ISSUE TITLE
Constraint ignored in ruleset, but respected as standalone.

### ISSUE THREAD

**Issue by oslego** [gss/engine#198]
Trying to constrain an element width to be half of another container's width. Defining the constraint in a ruleset is ignored, but it is accepted when defined as standalone constraint.

```css
#lead {
    /* This does not work as expected */
    width: == #hero[width] / 2;
}

/* This works as expected. */
#lead[width] == #hero[width] / 2;
```

See example:
http://codepen.io/oslego/pen/eNavPP

**Comment by paulyoung** [comment]
I believe this is a result of how scoped selectors work. The first ruleset is looking for and element with the ID of `hero` inside of an element with the ID of `lead`.

```css
#lead {
    /* This may work depending on your markup */
    width: == ^#hero[width] / 2;
}
```
