### ISSUE TITLE
Auto vendor prefix

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#21]
It's best to minimize how hard the solver is pushed, so:

``` css
.post {
      -webkit-column-gap: == [baseline];
         -moz-column-gap: == [baseline];
              column-gap: == [baseline];
    } 
```

creates 2 unused constraints & 2 unused constraint variables.  No good.

Definitely better to:

``` css
.post {
      column-gap: == [baseline];
    } 
```

and have GSS auto prefix during the display pass, after cassowary has solved.
