### ISSUE TITLE
Parse error: property colon in ruleset

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#24]
breaks when a space is between property and `:`, as with `width` below:

``` css
button {
    width : == ::[intrinsic-width] !require;
    height: == ::[intrinsic-height] !require;
}
```
