### ISSUE TITLE
Allow constraints based on element index within parent

### ISSUE THREAD

**Issue by jonrimmer** [gss/engine#31]
I would be cool if we could use elements' zero-based index within their parent in the RHS of constraints. Combined with slightly more sophisticated math functions this would let you do some fun things.

For example, given the following HTML...

``` html
<ul>
  <li class="box">...</li>
  <li class="box">...</li>
  <li class="box">...</li>
  <li class="box">...</li>
  <li class="box">...</li>
</ul>
```

...and the following hypothetical GSS...

``` css
[col-width] == ::window[width] / 3 !require;
@chain .box height();

.box {
  width: == [col-width];
  left: == (::[index] mod 3) * [col-width];
  top: == floor(::[index] / 3) * ::[height]
}
```

The boxes would form a wrapping grid of three columns...

```
+---+---+---+
|   |   |   |
+---+---+---+
|   |   |
+---+---+
```

Then you could add a CSS transition rule like this...

``` css
.box { transition: transform 0.3s ease; }
```

...and when the element order in the DOM changed, either due to a reordering of the list elements, or the addition/removal of items, they would all animate into their new positions.
