### ISSUE TITLE
Gotcha - display:none w/ intrinsic measurements

### ISSUE THREAD

**Issue by jasonkuhrt** [gss/engine#41]
When the page loads the layout is thus:

![screen shot 2014-03-28 at 9 59 07 am](https://cloud.githubusercontent.com/assets/284476/2550269/43013924-b681-11e3-88ef-0505204386fe.png)

Then, given a tug on the window size (any which way), `gss` lays out correctly:
![screen shot 2014-03-28 at 9 59 09 am](https://cloud.githubusercontent.com/assets/284476/2550270/50884eca-b681-11e3-8f61-d2532675abba.png)

See failing case at: http://jasonkuhrt.github.io/sandbox/

The `gss` code in question is:

``` css
body, html {width: 100%; height: 100%; margin: 0; padding: 0;}

html {
  font-size: 24px;
  text-align: center;
  font-family: Helvetica;
}

.box {
  center-x: == ::window[center-x];
  center-y: == ::window[center-y];
  width: <= ::window[width] / 2;
  height: == ::this[intrinsic-height];
  background: red;
  color: white;
}
```
