### ISSUE TITLE
Query Scope Gotcha

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#51]
Currently, query scopes are only inherited in rulesets (aka blocks), which leads to confusion when querying for elements...

If there are 10 `.box`'s on a page, 3 of which are inside `#item`, then the following creates 3 constraints:

``` css
    #item {
        .box {
            width: == 100;
        }
    }    
```

whereas, the following creates 10:

``` css
    #item {
        .box[width] == 100;
    }    
```

Should all the queries be lexically scoped?  Then could have a way to reach out of scope & query from root...
