### ISSUE TITLE
Non-numerical Vars 

### ISSUE THREAD

**Issue by d4tocchini** [gss/engine#70]
We've already come this far, might as well add support for variables for more than just numerical values.  

In the same style as constraint variables, only they cannot be constrained.  Maybe have to use a single `=` operator:

``` css
[font] = Georgia;

.box {
  font-family: [font];
}

@if [font] == Georgia {
  ...
}
```

Likewise, vars could be scoped to elements:

``` css
.box[my-color] = blue;

.box {
  border: 1px solid ::this[my-color];
}
```

Certainly feels better than the [Custom Properties for Cascading Variables Module Level 1](http://dev.w3.org/csswg/css-variables/)...
